version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=life_organizer
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=life_organizer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d life_organizer"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: